media:
  input: public
  output: /

content:
  - name: blog
    label: Blog Posts (TR)
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    filename: '{date}-{title}.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: date
        label: Publish Date
        type: date
        required: true
      - name: image
        label: Hero Image
        type: image
      - name: youtube_video
        label: YouTube Video ID
        type: string
        description: Sadece YouTube video ID'sini girin (örn: SOKm9dDOSC8)
      - name: tags
        label: Tags
        type: string
        list: true
      - name: layout
        label: Layout
        type: string
        hidden: true
        default: post
      - name: body
        label: Content
        type: rich-text
        required: true
    view:
      fields: [title, date, description]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc