name = "techoxium"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SESSION"
id = "techoxium-sessions"
preview_id = "techoxium-sessions-preview"

[observability]
enabled = true

[env.production]
name = "techoxium"

# Build configuration
[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"