name = "techoxium"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js/index.js"

[assets]
directory = "dist"
binding = "ASSETS_MANUAL"

# Add SESSION KV binding for Astro sessions
[[kv_namespaces]]
binding = "SESSION"
id = "317b48de29d246528905c76e9592a892"
preview_id = "e121541f75e04ac89d00131bb1376031"

[observability]
enabled = true

# Environment variables
[vars]
KEYSTATIC_GITHUB_CLIENT_ID = "Ov23liN27y5X4zgiO19x"
KEYSTATIC_GITHUB_CLIENT_SECRET = "51322a8dc0ef1aa0377559442919e24d071ceef5"
KEYSTATIC_SECRET = "08311b15eb98fdd93a85b1817ba69b86b1a26ba9ac4569417ac6a8ba8c5047ae"
SESSION_SECRET = "facec996e36f8aeb8508378bf16259d3af078a391e387db3f04d94466b844999"

# Build configuration - required for Pages Functions
[build]
command = "npm run build"
cwd = "."
