name = "techoxium"
compatibility_date = "2024-09-05"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js/index.js"

# Build configuration - required for Pages Functions
[build]
command = "npm run build:cloudflare"